spring:
  application:
    name: adouge-service-user
  cloud:
    nacos:
      config:
        shared-configs:
          - refresh: true
            data-id: ${spring.application.name}.yml
server:
  port: 8301


