server:
  port: 8001
spring:
  application:
    name: adouge-ops-admin
  security:
    user:
      name: adouge
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 120.24.101.194:8848 #配置Nacos地址
        metadata:
          user:
            name: adouge
            password: 123456
#开放所有端口
management:
  endpoints:
    web:
      exposure:
        include: '*'
